#!/bin/sh

username=$1
password=$2

for dir in *
do
	echo "======= Creating repository: gnustep-${dir}"
	delete_repo ${username} ${password} gnustep-${dir}
	create_repo ${username} ${password} gnustep-${dir}
	echo "Importing ${dir} into git..."
	cd ${dir}
	git remote rm origin
	git remote add origin git@github.com:gnustep/gnustep-${dir}.git
	git-setup
	git push -u origin master
	cd ..
	echo "====== Done: gnustep-${dir}"
done