#!/bin/sh
DIR=$1

echo "Executing update-gitsvn ${DIR}..."
${HOME}/bin/update-gitsvn ${DIR}
echo "Executing update-svndcommit ${DIR}..."
${HOME}/bin/update-svndcommit ${DIR}
#echo "Executing update-branches ${DIR}..."
#${HOME}/bin/update-branches ${DIR}

