#!/bin/sh
set -euo pipefail

DIR=$1
if [ -z "${DIR:-}" ]; then
	echo "Usage: update-gitsvn DIR" >&2
	exit 1
fi

echo "--- Updating ${DIR}"
cd "${DIR}"
echo "Date started..."
date

git svn fetch
git svn rebase

echo "Date completed..."
date
echo "-- finished"

if [ -n "${FORCE_PUSH:-}" ]; then
	git push --force-with-lease
else
	git push
fi

echo "--- Finished updating."
